In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
%matplotlib inline

In [5]:
df = pd.read_csv(
    "zomato.csv",
    engine="python",
    on_bad_lines="skip"
)
df

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555,https://www.zomato.com/bangalore/sea-spice-by-...,"1890, Shetty Gardenia, 9th Main, Kaverinagar, ...",Sea Spice by 7 Star,Yes,Yes,4.0/5,349,080 49653393,Banashankari,Casual Dining,"Sea Food, Neer Dosa, Anjal Masala Fry, Coconut...","Seafood, Biryani, Beverages, South Indian, Nor...","1,200","[('Rated 4.0', ""RATED\n Happened to go here w...","['Chicken Ghee Roast', 'Kori Ghassi', 'Chicken...",Dine-out,Banashankari
556,https://www.zomato.com/bangalore/mini-punjabi-...,"7/1, Behind BMS College Hostel, Hanumantha Nag...",Mini Punjabi Dhaba,Yes,No,4.2/5,287,+91 9845044074\r\r\r\r\n+91 7406012344,Banashankari,Quick Bites,"Panneer Butter Masala, Lassi, Paratha, Jeera R...",North Indian,350,"[('Rated 4.0', 'RATED\n This place was introd...",[],Dine-out,Banashankari
557,https://www.zomato.com/bangalore/onesta-banash...,"2469, 3rd Floor, 24th Cross, Opposite BDA Comp...",Onesta,Yes,Yes,4.6/5,2556,080 48653961\r\r\r\r\n080 48655715,Banashankari,"Casual Dining, Cafe","Farmhouse Pizza, Chocolate Banana, Virgin Moji...","Pizza, Cafe, Italian",600,"[('Rated 5.0', 'RATED\n I personally really l...",[],Dine-out,Banashankari
558,https://www.zomato.com/bangalore/wamama-banash...,"2466, Bhaskar Grand Tower, 24th Cross, Opposit...",Wamama,Yes,Yes,4.2/5,354,+91 8042111599\r\r\r\r\n+91 8971818009,Banashankari,Casual Dining,"Sushi, Noodles, Wine, Khau Suey, Mocktails, Ya...","Asian, Korean, Indonesian, Japanese, Chinese, ...",800,"[('Rated 4.0', 'RATED\n I really like the dec...","['Bok Choy and Tofu Dumpling [6 Pieces]', 'Chi...",Dine-out,Banashankari
559,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\r\r\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Dine-out,Banashankari

In [6]:
df.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 560 entries, 0 to 559
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          560 non-null    object
 1   address                      560 non-null    object
 2   name                         560 non-null    object
 3   online_order                 560 non-null    object
 4   book_table                   560 non-null    object
 5   rate                         508 non-null    object
 6   votes                        560 non-null    int64
 7   phone                        554 non-null    object
 8   location                     560 non-null    object
 9   rest_type                    560 non-null    object
 10  dish_liked                   253 non-null    object
 11  cuisines                     558 non-null    object
 12  approx_cost(for two people)  560 non-null    object
 13  reviews_list                 560 non-null    object
 14  menu_item                    560 non-null    object
 15  listed_in(type)              560 non-null    object
 16  listed_in(city)              560 non-null    object
dtypes: int64(1), object(16)
memory usage: 74.5+ KB

In [8]:
df.isnull().sum()

url                              0
address                          0
name                             0
online_order                     0
book_table                       0
rate                            52
votes                            0
phone                            6
location                         0
rest_type                        0
dish_liked                     307
cuisines                         2
approx_cost(for two people)      0
reviews_list                     0
menu_item                        0
listed_in(type)                  0
listed_in(city)                  0
dtype: int64

In [9]:
df.drop(['url','address','phone','menu_item','dish_liked','reviews_list','listed_in(city)'],axis=1,inplace=True)
df.head(5)

,name,online_order,book_table,rate,votes,location,rest_type,cuisines,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,Banashankari,Quick Bites,"South Indian, North Indian",300,Buffet
4,Grand Village,No,No,3.8/5,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600,Buffet

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 560 entries, 0 to 559
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         560 non-null    object
 1   online_order                 560 non-null    object
 2   book_table                   560 non-null    object
 3   rate                         508 non-null    object
 4   votes                        560 non-null    int64
 5   location                     560 non-null    object
 6   rest_type                    560 non-null    object
 7   cuisines                     558 non-null    object
 8   approx_cost(for two people)  560 non-null    object
 9   listed_in(type)              560 non-null    object
dtypes: int64(1), object(9)
memory usage: 43.9+ KB

In [11]:
df.isnull()

,name,online_order,book_table,rate,votes,location,rest_type,cuisines,approx_cost(for two people),listed_in(type)
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
555,False,False,False,False,False,False,False,False,False,False
556,False,False,False,False,False,False,False,False,False,False
557,False,False,False,False,False,False,False,False,False,False
558,False,False,False,False,False,False,False,False,False,False
559,False,False,False,False,False,False,False,False,False,False

In [12]:
df.isnull().sum()

name                            0
online_order                    0
book_table                      0
rate                           52
votes                           0
location                        0
rest_type                       0
cuisines                        2
approx_cost(for two people)     0
listed_in(type)                 0
dtype: int64

In [13]:
df.rename(columns={'name':'restaurants','book_table':'booking','rate':'rating','approx_cost(for two people)':'cost','listed_in(type)':'types'},inplace=True)
df.head(5)

,restaurants,online_order,booking,rating,votes,location,rest_type,cuisines,cost,types
0,Jalsa,Yes,Yes,4.1/5,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,Banashankari,Quick Bites,"South Indian, North Indian",300,Buffet
4,Grand Village,No,No,3.8/5,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600,Buffet

In [14]:
len(df)

560

In [15]:
df.dropna(inplace=True)

In [16]:
df.isnull().values.any()

np.False_

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 507 entries, 0 to 559
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   restaurants   507 non-null    object
 1   online_order  507 non-null    object
 2   booking       507 non-null    object
 3   rating        507 non-null    object
 4   votes         507 non-null    int64
 5   location      507 non-null    object
 6   rest_type     507 non-null    object
 7   cuisines      507 non-null    object
 8   cost          507 non-null    object
 9   types         507 non-null    object
dtypes: int64(1), object(9)
memory usage: 43.6+ KB

In [18]:
df[df.duplicated()].count().sum()

np.int64(0)

In [19]:
df.drop_duplicates(inplace=True)

In [20]:
df[df.duplicated()].count().sum()

np.int64(0)

In [21]:
df['rating'].unique()

array(['4.1/5', '3.8/5', '3.7/5', '3.6/5', '4.6/5', '4.0/5', '4.2/5',
       '3.9/5', '3.1/5', '3.0/5', '3.2/5', '3.3/5', '2.8/5', '4.4/5',
       '4.3/5', 'NEW', '2.9/5', '3.5/5', '2.6/5', '3.8 /5', '3.4/5',
       '4.5/5', '2.5/5', '2.7/5'], dtype=object)

In [22]:
df['rating'].replace("NEW|-",'0',regex=True).replace('/5','',regex=True).unique()

array(['4.1', '3.8', '3.7', '3.6', '4.6', '4.0', '4.2', '3.9', '3.1',
       '3.0', '3.2', '3.3', '2.8', '4.4', '4.3', '0', '2.9', '3.5', '2.6',
       '3.8 ', '3.4', '4.5', '2.5', '2.7'], dtype=object)

In [23]:
df['rating'].isnull().sum()

np.int64(0)

In [24]:
df['location'].unique()

array(['Banashankari', 'Basavanagudi', 'Mysore Road', 'Jayanagar',
       'Kumaraswamy Layout', 'Rajarajeshwari Nagar', 'Vijay Nagar',
       'Uttarahalli', 'JP Nagar', 'South Bangalore', 'City Market'],
      dtype=object)

In [25]:
df['location'].isnull().sum()

np.int64(0)

In [26]:
df['cost'].unique()

array(['800', '300', '600', '700', '550', '500', '450', '650', '400',
       '900', '200', '750', '150', '850', '100', '1,200', '350', '250',
       '950', '1,000', '1,500', '1,300', '199'], dtype=object)

In [27]:
df['cost'].isnull().sum()

np.int64(0)

In [28]:
df['cost'] = df['cost'].replace(",",'',regex=True).astype(int)

In [29]:
df.cost.unique()

array([ 800,  300,  600,  700,  550,  500,  450,  650,  400,  900,  200,
        750,  150,  850,  100, 1200,  350,  250,  950, 1000, 1500, 1300,
        199])

In [30]:
df['booking'].unique()

array(['Yes', 'No'], dtype=object)

In [31]:
df['booking'].isnull().sum()

np.int64(0)

In [32]:
df['online_order'].unique()

array(['Yes', 'No'], dtype=object)

In [33]:
df['online_order'].isnull().sum()

np.int64(0)

In [34]:
df['rest_type'].unique()

array(['Casual Dining', 'Cafe, Casual Dining', 'Quick Bites',
       'Casual Dining, Cafe', 'Cafe', 'Quick Bites, Cafe',
       'Cafe, Quick Bites', 'Delivery', 'Mess', 'Dessert Parlor',
       'Bakery, Dessert Parlor', 'Pub', 'Bakery', 'Takeaway, Delivery',
       'Fine Dining', 'Beverage Shop', 'Sweet Shop', 'Bar',
       'Dessert Parlor, Sweet Shop', 'Bakery, Quick Bites',
       'Sweet Shop, Quick Bites', 'Kiosk', 'Food Truck',
       'Quick Bites, Dessert Parlor', 'Beverage Shop, Quick Bites',
       'Beverage Shop, Dessert Parlor', 'Takeaway', 'Pub, Casual Dining',
       'Casual Dining, Bar', 'Dessert Parlor, Beverage Shop',
       'Quick Bites, Bakery', 'Microbrewery, Casual Dining'], dtype=object)

In [35]:
b = df['rest_type'].value_counts()
b

rest_type
Quick Bites                      208
Casual Dining                    104
Cafe                              49
Dessert Parlor                    36
Bakery                            16
Takeaway, Delivery                12
Delivery                          12
Sweet Shop                        12
Beverage Shop                      9
Casual Dining, Cafe                5
Bar                                4
Cafe, Casual Dining                4
Beverage Shop, Quick Bites         4
Sweet Shop, Quick Bites            4
Casual Dining, Bar                 3
Beverage Shop, Dessert Parlor      3
Bakery, Quick Bites                3
Cafe, Quick Bites                  2
Quick Bites, Cafe                  2
Bakery, Dessert Parlor             2
Dessert Parlor, Sweet Shop         2
Fine Dining                        1
Mess                               1
Pub                                1
Quick Bites, Dessert Parlor        1
Food Truck                         1
Kiosk                              1
Takeaway                           1
Pub, Casual Dining                 1
Dessert Parlor, Beverage Shop      1
Quick Bites, Bakery                1
Microbrewery, Casual Dining        1
Name: count, dtype: int64

In [36]:
df['types'].unique()

array(['Buffet', 'Cafes', 'Delivery', 'Desserts', 'Dine-out'],
      dtype=object)

In [37]:
df['types'].value_counts()

types
Delivery    418
Desserts     51
Cafes        24
Buffet        7
Dine-out      7
Name: count, dtype: int64

In [38]:
df['cuisines'].isnull().sum()

np.int64(0)

In [39]:
df['cuisines'].value_counts()

cuisines
South Indian                                  32
North Indian                                  22
North Indian, Chinese                         20
Bakery, Desserts                              13
Fast Food                                     13
                                              ..
Tea, Beverages                                 1
Beverages, Juices, Desserts, Italian           1
Mithai, Street Food, North Indian, Chinese     1
Bakery, Street Food                            1
Continental, Asian, North Indian, Tea          1
Name: count, Length: 244, dtype: int64

In [40]:
df['restaurants'].unique()

array(['Jalsa', 'Spice Elephant', 'San Churro Cafe',
       'Addhuri Udupi Bhojana', 'Grand Village', 'Timepass Dinner',
       'Rosewood International Hotel - Bar & Restaurant', 'Onesta',
       'Penthouse Cafe', 'Smacznego',
       'CafÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â\x83Ã\x83Â\x83Ã\x82Â\x82Ã\x83Â\x82Ã\x82Â© Down The Alley',
       'Cafe Shuffle', 'The Coffee Shack', 'Caf-Eleven', 'Cafe Vivacity',
       'Catch-up-ino', "Kirthi's Biryani", 'T3H Cafe',
       '360 Atoms Restaurant And Cafe', 'The Vintage Cafe',
       'Woodee Pizza', 'Cafe Coffee Day', 'My Tea House', 'Hide Out Cafe',
       'CAFE NOVA', 'Coffee Tindi', 'Sea Green Cafe', 'Cuppa',
       "Srinathji's Cafe", 'Redberrys', 'Foodiction', 'Sweet Truth',
       'Ovenstory Pizza', 'Faasos', 'Behrouz Biryani', 'Fast And Fresh',
       'Szechuan Dragon', 'Empire Restaurant',
       'Maruthi Davangere Benne Dosa', 'Chaatimes', 'Havyaka Mess',
       "McDonald's", "Domino's Pizza", 'Hotboxit', 'Kitchen Garden',
       'Recipe', 'Beijing Bites', 'Tasty Bytes', 'Petoo',
       'Shree Cool Point', 'Corner House Ice Cream', 'Biryanis And More',
       'Roving Feast', 'FreshMenu', 'Banashankari Donne Biriyani',
       'Wamama', 'Five Star Chicken', 'XO Belgian Waffle',
       'Peppy Peppers', 'Goa 0 Km', 'Chinese Kitchen', '1947',
       'Cake of the Day', 'Kabab Magic', "Namma Brahmin's Idli",
       'Gustoes Beer House', 'Sugar Rush', 'Burger King', 'The Good Bowl',
       'The Biryani Cafe', 'Spicy Tandoor', 'LSD Cafe', 'Rolls On Wheels',
       'Om Sri Vinayaka Chats',
       'Sri Guru Kottureshwara Davangere Benne Dosa',
       'Devanna Dum Biriyani Centre', 'Kolbeh', 'Upahar Sagar',
       'Kadalu Sea Food Restaurant', 'Frozen Bottle', 'Parimala Sweets',
       'Vaishali Deluxe', 'The Big O Bakes', 'Meghana Foods',
       'Krishna Sagar', 'Dessert Rose', 'Chickpet Donne Biryani House',
       "Thanco's Natural Ice Creams", 'Nandhini Deluxe',
       "Vi Ra's Bar and Restaurant", 'Kaggis', 'Ayda Persian Kitchen',
       'Chatar Patar', 'Polar Bear', "Kidambi's Kitchen", 'Mane Thindi',
       'Kotian Karavali Restaurant', 'Floured-Baked With Love',
       'Cakes & Slices', 'Spice 9', 'Naveen Kabab & Biriyani Mane',
       'Katriguppe Donne Biryani', 'Hari Super Sandwich',
       'Atithi Point Ande Ka Funda', 'Just Bake', 'K27 - The Pub',
       'Bengaluru Coffee House', 'New Mangalore Lunch Home',
       'Coffee Bytes', 'Parjanya Chat Zone',
       "Kwality Wall's Swirl's Happiness Station", 'Ruchi Maayaka',
       'Roll Magic Fast Food', 'Foodlieious Multi Cuisine',
       'Thanishka Nati And Karavali Style', 'Melting Melodies',
       'New Indraprasta', 'Anna Kuteera', 'Darbar', 'Vijayalakshmi',
       'Sri Udupi Food Hub', 'Udupi Upahar', 'House Of Kebabs',
       'Roll N Rock', 'BOX8- Desi Meals', 'KFC', 'Bitez', 'Roll Over',
       'Imperial Restaurant', 'Lassi Shop', 'The Fortuna', 'Wahab',
       'Al Diwan Biryanis And More', "New Gowda's Fried Chicken",
       'Canton', 'Diabetics Dezire Sugarless Sweets and Bakes',
       'The Blue Wagon - Kitchen', 'HOT COFFEE', 'Patio 805',
       'Lassi Corner', 'Sagar Deluxe', 'Kanti Sweets', 'Vegetalia',
       'Aramane Donne Biryani', 'Ande Ka Funda', 'Cake Ghar',
       'Energy Addaa', 'Bhattara Bhojana', 'Tandoori Knight',
       'Dev Sagar - Food Street', 'Mitraa Da Pizza', 'Paradise Premium',
       'Grazers', 'Shakes Theory', '@Italy', 'Chilli Flakes',
       'Calcutta Cafe', 'Old Mumbai Ice Cream', 'Donne Biriyani House',
       'By 2 Coffee', "Kedia's Fun Food", 'Davangere Butter Dosa Hotel',
       'Just Shawarma', 'Mini Punjabi Dhaba', 'Mulabagilu Dosa',
       'Gokul Veg', 'Olive - Era', 'Udupi Ruchi',
       'Madhappa Hindu Military Hotel', 'Gama Gama', 'Pizza Hut',
       'Mangalore Pearl', 'Asha Sweets Centre', 'Twiststick House',
       'Cool Corner', 'Pizza Mane', 'Dal Tadkaa', 'Chutney Chang',
       'Mystique Palate', 'Thamboola', 'Castle Rock',
       'Vietnamese Kitchen', 'C Corner', 'Paratha Merchant',
       'North Rasoe', 'Toscano', 'Lord Of The Kitchen', 'Stoned Monkey',
       'Central Jail Restaurant', 'Bella', 'Vennela Andhra Meals',
       'New Prashanth Hotel', 'The Grillo', 'Re Malnad Nati Style Hotel',
       'Karma Kaapi', "Tiwari's", 'Pizza Stop', "Biggies Burger 'n' More",
       "Kollapuri's", 'Kadamba Classic', 'RS Shiv Sagar', 'Kholi Mane',
       'Harshi Super Sandwich', 'Cake Yard', 'Sri Udupi Veg', 'Cake Art',
       'Potato House', 'Matru Sagar', 'Ugadi', 'Sri Krishna Sweets',
       'In Time Cane Juice', 'Subway', 'Daal Roti', 'The Lassi Park',
       'A2B - Adyar Ananda Bhavan', 'Srikrishna Bhavan', 'Green Gardenia',
       'J Spice', 'Karavali Family Restaurant', 'Karavali Lunch Home',
       'Hatti Kaapi', "Kolkata Kathi Roll's", 'Upahara Darshini',
       'The Chaat Shop', 'Anda Ka Funda', 'Shri Vinayaka Ice N Juice',
       'Ibaco', 'Jalaram Sweets', 'Samskruti - Sanman Gardenia',
       'Bendakaluru Bytes', 'Cocoa Bakes', 'Chumma Delicious',
       'SSV Upahar', 'Dwaraka Grand', 'Gufha - The President Hotel',
       "Tanna's Kitchen", 'Shree Mandarathi Grand',
       'Mojo Pizza - 2X Toppings', 'Iceberg Icecreams', 'South Kitchen',
       'Chung Wah', 'Shanthi Sagar', 'Millet Mama',
       'Bangarpet Chat Express', 'Prems Graama Bhojanam', 'Java City',
       'Kamat Bugle Rock', 'Puliyogare Point', 'Bangalore Agarwal Bhavan',
       'Rustic Stove', 'Udupi Ruchi Grand', 'De Thaali', 'Just Thindi',
       'Vasanth Vihar - Since 1965', 'Sea Spice by 7 Star', 'Desi Dawat',
       'Cafe Aira', 'Mast Punjabi', 'South Grand', 'The Pizzeria',
       'Cafe Zone', 'Ruchis Point', 'Firangi Bake',
       'The Royal Corner - Pai Viceroy', 'Hara Fine Dine', 'Chocoberry',
       'Dakshin Grand', 'Sandwichwallas', 'Chai Mane', 'SLV Upachar',
       'Waffle-A-Go Go', 'Cross Road Cafe', 'Anand Donne Biriyani',
       'Seven Star', "Stop 'N' Joy", 'Sri Yaksha Shiv Sagar', 'Fudge',
       'Just Bunny', 'Bakers Town', 'Shree Mahalakshmi Sweets',
       'Kaapi Kendra', 'Ivy', 'The Airos', 'Chai Kraft',
       'South Point Pub', 'The Trundle', 'The Krishna Grand Xpress',
       'Sri Krishna Darshini', 'Shringar Sweets & Snacks', 'Udupi Grand',
       'Ganesh Grand', 'Shreyas Upahar & Burger Point', 'Little Cafe',
       'Mumbai Badam Milk & Lassi Center', 'Sri Krishna Sagar',
       'Mylari Biryani Family Restaurant', '1980s Games Cafe',
       'Kadala Tarangaa', 'Namma Biryani', "Nandhanu's Rasoi",
       'Hotel Pork Paradise', 'As On Fire', 'J K Fish Land',
       'Curry Leaves', 'Magic Meals', 'Desi Cream Junction',
       'Drunken Monkey', "Ruchi's Corner", 'Tandoori Bytes',
       'Bangalore Donne Biriyani', 'SGS Non Veg - Gundu Pulav',
       'Keventers', 'Navi Food Point', 'Shawarma Inc',
       'The Cafe Nuts and Bolts', 'AM WOW', 'Lalbagh Grand',
       'Funjabi Curries', 'Eat Repeat', 'Salut', 'Nammura Donne Biriyani',
       'Lassi Stop', 'Dakshin Kitchen', 'Sri Sai Cafe',
       'Sri Sai 99 Variety Dosa', 'Utsav Restaurant', 'Crunch and Munch',
       'Food Geek', 'Sri Krishna Aramane', 'Great Indian Rolls',
       'Chats Point', 'Food Point', 'Swarga Ruchi', 'Kolkata King',
       "Sandwich Mama's And Frozen Monster", 'New Rajadhani Spicy',
       'Big Mishra Pedha', 'VEGeatz', 'Foodizo', 'Food Springs',
       "Chung's Chinese Corner",
       'Eurasia Pasta and Barbeque by Little Italy',
       'Goli Vada Pav No. 1', "Ragoo's", 'Pure & Natural', 'Maiyas',
       'Sip n Dine', 'Cafe Mondo', 'Jalpaan', "Kataria's Pakwan",
       'Juicy Momos', 'Amande Patisserie', 'Anand Sweets and Savouries',
       'Chicken Hunt', 'Swadesh Tadka', 'Cane-O-La', 'New Biryani Mane',
       'Karnataka Bhel House', 'Sreeraj Lassi Bar',
       'Juice Junction Food Court', "Bunt's Biriyani Palace",
       'Chai Point', 'Janahaar', 'Utsav', 'Meat And Eat', 'Snacks Bite',
       'The Spice Saga', 'Dakshin Cafe', 'Kaulige Millet Corner',
       'Ifruit Ice Cream', 'Havmor', 'Grand Food', 'Dining Hut',
       'Desi Swaad', 'Yummy Momos', 'Masale Daan', 'Grow Fit',
       'Sandwich Hub', 'Udupi Sri Krishna Cafe',
       'Starlite Bakery & Fastfood', 'Veganbreak24x7', 'Aadhya Hotel',
       'Dodda Mane Baaduta', 'Swadd Kitchen', 'Happy Chopsticks',
       'Sai Super Sandwich', 'Right Pizza', 'Udupi Upachar',
       'Davanagere Benne Dose Hut', 'The Sip Shop', 'Subz',
       'Sri Banashankari Upahara', 'Mint and Mustard', 'Chinese Square',
       'Hyderabad Express', 'Punjabi Raswada', "Vinny's",
       "Chetty's Corner", "Kapoor's Cafe", 'Donne Biryani & Kabab Corner',
       'Sukh Sagar', 'S M V Snacks Corner', 'Andhra Ruchulu',
       'Steaming Mugs', 'Rajathadri Food Fort', 'Brew Meister', 'Rasoi',
       'Mr. Singh Da Dhaba', 'Kababs N Biryani', 'Ayodhya Upachar',
       'Biriyani Mane', 'Cafe Ajfan', 'Brundhavana Food Point',
       'SLV Corner Restaurant', 'Biryani Royals Garden',
       'Hotel New Karavali', 'The Krishna Grand', 'Roti Ghar',
       'Multi Snacky Hub', 'Kettle & Kegs', 'Baisakhi', 'Poonam Sweets',
       "Amma's Pastries", 'The Lassi and Juice Park', 'Corner Stone',
       'Arun Ice Cream', 'Sweet N Swirl', 'Gopi Ice Creams',
       'Sri Venkateshwara Sweet Meat Stall', 'Baskin Robbins',
       'Srinivasa Brahmins Bakery', 'Jain Bakes', 'KC Das - Sweet Spot',
       'A2B Veg - Adyar Ananda Bhavan'], dtype=object)

In [41]:
df.groupby('restaurants').count().head()

,online_order,booking,rating,votes,location,rest_type,cuisines,cost,types
restaurants,,,,,,,,,
1947,1,1,1,1,1,1,1,1,1
1980s Games Cafe,1,1,1,1,1,1,1,1,1
360 Atoms Restaurant And Cafe,2,2,2,2,2,2,2,2,2
@Italy,1,1,1,1,1,1,1,1,1
A2B - Adyar Ananda Bhavan,1,1,1,1,1,1,1,1,1

In [42]:
df['restaurants']=df['restaurants'].str.replace('[Ãx][^A-Za-z]+','',regex=True)

In [43]:
df.groupby('restaurants').count().head()

,online_order,booking,rating,votes,location,rest_type,cuisines,cost,types
restaurants,,,,,,,,,
1947,1,1,1,1,1,1,1,1,1
1980s Games Cafe,1,1,1,1,1,1,1,1,1
360 Atoms Restaurant And Cafe,2,2,2,2,2,2,2,2,2
@Italy,1,1,1,1,1,1,1,1,1
A2B - Adyar Ananda Bhavan,1,1,1,1,1,1,1,1,1

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 507 entries, 0 to 559
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   restaurants   507 non-null    object
 1   online_order  507 non-null    object
 2   booking       507 non-null    object
 3   rating        507 non-null    object
 4   votes         507 non-null    int64
 5   location      507 non-null    object
 6   rest_type     507 non-null    object
 7   cuisines      507 non-null    object
 8   cost          507 non-null    int64
 9   types         507 non-null    object
dtypes: int64(2), object(8)
memory usage: 43.6+ KB

In [45]:
df.isnull().sum()

restaurants     0
online_order    0
booking         0
rating          0
votes           0
location        0
rest_type       0
cuisines        0
cost            0
types           0
dtype: int64

In [46]:
df.to_csv('./clean_zomato.csv')

In [47]:
type1=df['rest_type'].value_counts().head(5)
type1.to_frame()

                count
rest_type
Quick Bites       208
Casual Dining     104
Cafe               49
Dessert Parlor     36
Bakery             16

•	Restaurant Type

In [48]:
fig = px.bar(x= type1.index,
             y= type1,
            color= type1.index,
            title='Restaurant type',labels={'x':'Restaurant','y':'Count of Restaurant'}
            )
fig.show()

In [49]:
fig=px.bar(x=type1.index,
           y=type1,
           color=type1.index # Each bar is colored differently
           ,title='Restaurant type',labels={'x':'Restaurant','y':'Count of Restaurant'} # changes x and y label
          )
fig.show()

•	Restaurants delivering Online or not

In [50]:
online_or_not = df['online_order'].value_counts()
online_or_not

online_order
Yes    402
No     105
Name: count, dtype: int64

In [51]:
fig2 = px.pie(online_or_not,
             title = ' Delivering Online or Not',
              values = online_or_not,
              names = online_or_not.index
             )
fig2.show()

•Restaurants allowing table booking or not

In [52]:
df['booking'].value_counts()

booking
No     471
Yes     36
Name: count, dtype: int64

In [80]:
fig = px.bar(df,x='booking', color = 'booking'
    ,title="table booking or not"
)
fig.update_layout(
    width=700,   # 👈 change this
    height=450   # 👈 and this
)





fig.show()

•	Table booking Rate vs Rate

In [81]:
fig= px.box(df,x='booking',
               y='rating',
            color='booking'
               )
fig.update_layout(
    width=700,   # 👈 change this
    height=450   # 👈 and this
)


fig.show()

Online Order vs Rate

In [82]:
fig = px.violin(df,x='online_order', y="rating",
                color='online_order',

                 # draw box plot inside the violin
                points='outliers', # can be 'outliers', or False
               )
fig.update_layout(
    width=700,   # 👈 change this
    height=450   # 👈 and this
)


fig.show()

•	Best Location

In [56]:
loc_vote = df.groupby('location')['votes'].sum()
loc_vote = loc_vote.nlargest(5).sort_values()
loc_vote

location
Rajarajeshwari Nagar      732
Kumaraswamy Layout       5676
Basavanagudi            13655
Jayanagar               34854
Banashankari            50496
Name: votes, dtype: int64

In [83]:
fig = px.bar(x=loc_vote.index,
            y= loc_vote,
            color=loc_vote.index,
             title ='Best Location',labels={'x':'location','y':'votes'}
            )
fig.update_layout(
    width=700,   # 👈 change this
    height=450   # 👈 and this
)


fig.show()

•	Cost of Restaurant

In [84]:
fig = px.histogram(df['cost'],nbins=100)
fig.update_layout(
    width=700,   # 👈 change this
    height=450   # 👈 and this
)


fig.show()

In [59]:
df['rating'] = (
    df['rating']
    .astype(str)
    .str.split('/')
    .str[0]
)

df['rating'] = pd.to_numeric(df['rating'], errors='coerce')

In [60]:
vote = (
    df.groupby('restaurants', as_index=False)
      .agg({
          'votes': 'mean',
          'rating': 'mean'
      })
      .sort_values(by=['rating', 'votes'], ascending=False)
      .head(10)
)

Best Location by Votes

(Relation between Location and Votes)

In [61]:
fig = px.bar(
    x=loc_vote.index,
    y=loc_vote.values,
    color=loc_vote.index,
    title='Best location by votes',
    labels={'x': 'Location', 'y': 'Votes'}
)
fig.update_layout(
    width=700,   # 👈 change this
    height=450   # 👈 and this
)


fig.show()

Best Location by Rating

(Relation between Location and Rating)

In [62]:
fig=px.bar(y=vote['rating'],
           x=vote.index,
           color=vote.index # Each bar is colored differently
           ,title='Best location by rating',labels={'x':'Location','y':'Rating'} # changes x and y label
          )
fig.update_layout(
    width=700,   # 👈 change this
    height=400   # 👈 and this
)

fig.show()

Relation between cost and rating

In [78]:
fig=px.scatter(df,x='cost',y='rating',color='online_order')
fig.update_layout(
    width=700,   # 👈 change this
    height=450   # 👈 and this
)


fig.show()

Relation between Location and Type

In [79]:
fig = px.bar(df,x="types",y ="rating",color='types')
fig.update_layout(
    width=700,   # 👈 change this
    height=450   # 👈 and this
)


fig.show()

•	No. of restaurants in a Location

In [92]:
df.head(5)

,restaurants,online_order,booking,rating,votes,location,rest_type,cuisines,cost,types
0,Jalsa,Yes,Yes,4.1,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800,Buffet
1,Spice Elephant,Yes,No,4.1,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800,Buffet
2,San Churro Cafe,Yes,No,3.8,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7,88,Banashankari,Quick Bites,"South Indian, North Indian",300,Buffet
4,Grand Village,No,No,3.8,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600,Buffet

In [95]:
fig = px.bar(df,x="location",color='location')
fig.show()

•	Gaussian Rest type and Rating

•	Most famous restaurant chains in Bengaluru

In [100]:
fam = df['restaurants'].value_counts()
fam

restaurants
San Churro Cafe                  4
Kirthi's Biryani                 3
Onesta                           3
Redberrys                        3
CAFE NOVA                        3
                                ..
Donne Biriyani House             1
Calcutta Cafe                    1
Chilli Flakes                    1
@Italy                           1
Madhappa Hindu Military Hotel    1
Name: count, Length: 434, dtype: int64

In [104]:
top_chains_df = fam.reset_index()
top_chains_df.columns = ['Restaurant_Name', 'Outlet_Count']
top_chains_df.columns

Index(['Restaurant_Name', 'Outlet_Count'], dtype='object')

In [106]:
top_chains_df = top_chains_df.sort_values(
    by='Outlet_Count',
    ascending=False
)

In [111]:
import plotly.express as px

fig = px.bar(
    top_chains_df,
    x='Restaurant_Name',
    y='Outlet_Count',
    color='Restaurant_Name',
    orientation='h',
    title='Most Famous Restaurant Chains in Bengaluru'
)
fig.show()